### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/openrefine-socialsci#75] opened 2020-09-29 09:05 UTC
From https://datacarpentry.org/lessons/#social-science-curriculum

https://datacarpentry.org/openrefine-socialsci/reference.html
leads to 404
but the following is present
https://github.com/datacarpentry/openrefine-socialsci/blob/gh-pages/reference.md

How do we correct this?

**Comment by brownsarahm** [comment] 2020-09-29 17:43
Thanks @annajiat I believe the issue is that the sending page has an old format to the urls.  I suggested a change there and tagged appropriate staff if the change should be fixed across lesson repos instead.

**Comment by brownsarahm** [comment] 2020-09-30 14:21
@annajiat I've put in a PR to fix it, waiting on another maintainer. 

Thanks for helping discover this issue and inconsistency across our repos!

**Closed** 2020-09-30 14:24 UTC
